//
//  StaticDatasource.swift
//  Swish
//
//  Created by Benjamin Heutmaker on 10/24/15.
//  Copyright © 2015 Ben Heutmaker. All rights reserved.
//

import Foundation

let allProducts: [Product] = [
    
    Product(imageString: "1", price: 25.0, productDescription: "The dress leaves her shoulders mostly uncovered and flows down into a tasteful keyhole neckline. It's a relaxed fit which makes the dress look comfortable, yet elegant and stylish.\nHer arms have been covered to about her elbows. The sleeves are a loose fit and, in a way, help put focus on her soft skin.\nThe dress' waist is thin, but it's a tight fit. A cloth ribbon has been wrapped around her and tied in the front.\nBelow the waist the dress fits snug around her and has a sarong style. The dress reaches to just above her knees and is longer in the back.\nShe's wearing t-straps, which matches the dress perfectly. To top it all of she's wearing a subtle necklace and one simple, but elegant bracelet."),
    
    Product(imageString: "2", price: 50.0, productDescription: "The dress leaves her shoulders mostly uncovered and flows down into a beautiful scoop neckline. It's a relaxed fit which makes the dress look comfortable, yet elegant and stylish.\nHer arms have been covered to just above her wrists. The sleeves broaden towards the bottom, allowing for bracelets to be visisble.\nThe dress' waist is wide, but it's a slim fit. A small, elegant belt helps accentuate her waist without being too much.\nBelow the waist the dress widens and has several asymmetric layers towards the bottom. The dress reaches all the way down, almost covering her feet and is longer at the sides and back of the dress.\nShe's wearing peep toes, they're simple, but radiate grace and refinement. To top it all of she's wearing a simple, but stylish hat and small, stylish earrings."),
    
    Product(imageString: "3", price: 35.99, productDescription: "The dress covers only a small portion of her shoulders and flows down into a modest jewel neckline. It's a relaxed fit which removes the focus from her breasts, but without making it look sloppy.\nHer arms are only covered at her shoulders. Which is a good thing too, her silky skin isn't something you want to cover up.\nThe dress' waist is thin, but it's a comfortable fit. A bow has been wrapped around her waist and positioned slightly to one side.\nBelow the waist the dress widens and forms a round, balloon-style dress. The dress reaches to well above her ankles and is slightly longer at the sides and back of the dress.\nShe's wearing slingbacks, an ideal match for this dress. To top it all of she's wearing an ornate necklace and several jeweled bracelets."),
    
    Product(imageString: "4", price: 24.99, productDescription: "The dress covers just one of her shoulders, leaves the other uncovered and flows down into a beautiful cowl neckline. It's a snug fit which adds to the grace and elegance of the dress.\nHer arms have been covered to just above her elbows. The sleeves broaden towards the bottom and playfully accentuate her skin.\nThe dress' waist is narrow, but it's a loose fit. A cloth ribbon has been wrapped around her and tied in the front.\nBelow the waist the dress widens and has a box pleated style. The dress reaches all the way down to her feet and is slightly longer at the sides.\nShe's wearing stilettos, an ideal match for this dress. To top it all of she's wearing a subtle necklace and several lavish bracelets."),
    
    Product(imageString: "5", price: 69.99, productDescription: "The dress covers her shoulders only barely with 2 spaghetti straps and flows down into a modest court neckline. It's a snug fit which makes the dress look smart and stylish.\nHer arms have been covered completely. The sleeves are a loose fit from top to bottom, giving the dress a slightly casual look.\nThe dress' waist is thin, but it's a loose fit. It's left simple, elegant and undecorated, creating a look that flows from top to bottom.\nBelow the waist the dress widens and has a ruffle style from top to bottom. The dress reaches all the way down to her feet and is the same length all around.\nShe's wearing wedges, gorgeous on their own, an ideal match in combination with the dress . To top it all of she's wearing a gorgeous wide hat and small, stylish earrings."),
    
    Product(imageString: "6", price: 49.00, productDescription: "The dress leaves her shoulders uncovered, instead it's supported around her neck and flows down into a fancy sweetheart neckline. It's a loose fit which makes the dress look comfortable, yet elegant and stylish.\nHer arms have been covered all the way down to her wrists. The sleeves are a tight, but comfortable fit from top to bottom, allowing for enough movement while still looking stylish.\nThe dress' waist is thin, but it's a slim fit. A bow has been wrapped around her waist and positioned slightly to one side.\nBelow the waist the dress fits snug around her and has a straight style. The dress reaches to just below her knees and is longer in the back.\nShe's wearing ballerina flats, no other shoe would've matched this dress better. To top it all of she's wearing a bow in her hair and several lavish bracelets.")
]